### ISSUE TITLE
Error at 'genmod models' rule

### ISSUE THREAD

**Issue by leahkemp** [ESR-NZ/vcf_annotation_pipeline#19]
Pipeline is erroring out at the [genmod models rule](https://github.com/ESR-NZ/vcf_annotation_pipeline/blob/v1.1.0/workflow/rules/genmod_models.smk).

My error:

```bash
AttributeError: module 'collections' has no attribute 'Iterable'
```

It looks to be a missing python dependency not accounted for in the [conda environment file for this rule](https://github.com/ESR-NZ/vcf_annotation_pipeline/blob/v1.1.0/workflow/envs/genmod.yaml). More specifically, it looks like I was now using a newer version of python (v3.10) that wasn't pinned down which caused the error. I was able to resolve this by adding a python dependancy to the [said conda environment](https://github.com/ESR-NZ/vcf_annotation_pipeline/blob/v1.1.0/workflow/envs/genmod.yaml), so it becomes:

```yaml
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::pip =20.2.2
  - python=3.7
  - pip:
    - genmod==3.7.3
```

I don't know if I'll get around to implementing a fix for this, but I'm recording the bug here in case others come across this issue and it hurts their heads. Others are more than welcome to pick up this issue and fix if you feel so inclined :)
